### ISSUE TITLE
direct menu items

### ISSUE THREAD

**Issue by chocolatemelt** [chocolatemelt/fe-cli#7]
menu items need to actually -do- something!

**Comment by sihsob** [comment]
Few questions:
1. What options should be implemented?
2. How should rosters be set and saved?  Also are all characters unlocked from the beginning?

**Comment by chocolatemelt** [comment]
play and options (and by extension saving) are the biggest priorities atm

characters are definitely not unlocked from the beginning unless a campaign creator wants to make the campaign that way (we'll just be modeling it after the story in FE:A for now)

roster saving is up in the air, but it definitely should be saved to some home file

**Comment by chocolatemelt** [comment]
see 57954e2 for examples
