### ISSUE TITLE
retrieve logo data more robustly

### ISSUE THREAD

**Issue by chocolatemelt** [chocolatemelt/fe-cli#8]
currently only works when running the program from the repository root because it uses a relative path; possible to get absolute path?

**Comment by sihsob** [comment]
Is there a way to set up the path when installing the program?  Maybe in Cmake file? (This issue is also relevant to any data files used)

**Comment by chocolatemelt** [comment]
best way would be to store it in the same location as save data and then grab it that way, but I don't like this method since it's not something that's being changed often (or at all really)
